# Assignment 3

Task 1

1.

In [3]:
def err():
    try:
        n=5/0
    except ZeroDivisionError:
        print("cannot divide number by zero")
        
err()

cannot divide number by zero


2.

In [4]:
def func(list1,list2,list3):
    for i in list1:
        for j in list2:
            for k in list3:
                print(i+" "+j+" "+" "+k)
list1=["America","India"]
list2=["play","watch"]
list3=["baseball","cricket"]
func(list1,list2,list3)

America play  baseball
America play  cricket
America watch  baseball
America watch  cricket
India play  baseball
India play  cricket
India watch  baseball
India watch  cricket


TASK 2

1.

In [5]:
import numpy as np
def matrix(v,n,inc=False):
    
    if not inc:
        arr1 = np.array([x**(n-1-i) for x in v for i in range(n)]).reshape(v.size,n)
    elif inc:
        arr1 = np.array([x**i for x in v for i in range(n)]).reshape(v.size,n)
    
    return arr1

In [6]:
print(matrix(np.array([1,2,3,4]),5,False))

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]]
